// components/chapter/PhaseGate.vue
<script setup lang="ts">
import { computed, watch } from 'vue'
import { BookCheck, FlaskConical, Brain, PartyPopper } from 'lucide-vue-next'
import { useProgressStore } from '~/stores/progress'

const props = defineProps<{
  chapterId: string
  partColor: string
}>()

const store = useProgressStore()
const progress = computed(() => store.getProgress(props.chapterId))

const phases = computed(() => [
  {
    id: 'read',
    label: 'Reading',
    icon: BookCheck,
    done: progress.value.phases.read,
  },
  {
    id: 'exercise',
    label: 'Exercise',
    icon: FlaskConical,
    done: progress.value.phases.exercise,
  },
  {
    id: 'quiz',
    label: 'Quiz',
    icon: Brain,
    done: progress.value.phases.quiz.passed,
  },
])

const allComplete = computed(() => phases.value.every(p => p.done))

// Fire confetti when all phases complete
watch(allComplete, async (isComplete) => {
  if (!isComplete) return
  if (import.meta.server) return

  try {
    const confetti = (await import('canvas-confetti')).default
    confetti({
      particleCount: 120,
      spread: 80,
      origin: { y: 0.7 },
      colors: [props.partColor, '#4a6aff', '#00c896', '#f0a500'],
    })
  } catch {
    // canvas-confetti not available; silently skip
  }
})
</script>

<template>
  <div class="mt-12">
    <div class="section-divider mb-10" />

    <div class="glass-panel rounded-xl p-6">
      <h3 class="font-display text-base font-semibold text-white mb-5">
        Chapter Progress
      </h3>

      <!-- Phase indicators -->
      <div class="grid grid-cols-3 gap-3">
        <div
          v-for="phase in phases"
          :key="phase.id"
          class="relative flex flex-col items-center gap-2 py-3 rounded-lg transition-colors duration-300"
          :class="phase.done ? 'bg-white/[0.04]' : 'bg-white/[0.02]'"
        >
          <!-- Icon circle -->
          <div
            class="w-10 h-10 rounded-full flex items-center justify-center transition-all duration-300"
            :style="{
              backgroundColor: phase.done ? `${partColor}20` : 'rgba(255,255,255,0.05)',
              boxShadow: phase.done ? `0 0 16px ${partColor}20` : 'none',
            }"
          >
            <component
              :is="phase.icon"
              class="w-4 h-4 transition-colors duration-300"
              :style="{ color: phase.done ? partColor : 'rgba(255,255,255,0.25)' }"
            />
          </div>

          <!-- Label -->
          <span
            class="text-xs font-medium transition-colors duration-300"
            :class="phase.done ? 'text-white/80' : 'text-white/30'"
          >
            {{ phase.label }}
          </span>

          <!-- Status dot -->
          <span
            class="absolute top-2 right-2 w-2 h-2 rounded-full transition-colors duration-300"
            :style="{
              backgroundColor: phase.done ? partColor : 'rgba(255,255,255,0.1)',
            }"
          />
        </div>
      </div>

      <!-- Complete banner -->
      <Transition
        enter-active-class="transition-all duration-500 ease-out"
        enter-from-class="opacity-0 translate-y-2"
        enter-to-class="opacity-100 translate-y-0"
      >
        <div
          v-if="allComplete"
          class="mt-4 flex items-center justify-center gap-2 py-3 rounded-lg"
          :style="{ backgroundColor: `${partColor}15` }"
        >
          <PartyPopper class="w-4 h-4" :style="{ color: partColor }" />
          <span class="text-sm font-semibold" :style="{ color: partColor }">
            Chapter Complete!
          </span>
        </div>
      </Transition>
    </div>
  </div>
</template>

// src/components/chapter/PhaseGate.tsx
'use client';
import { CheckCircle2, Circle, Lock } from 'lucide-react';

interface PhaseGateProps {
  read: boolean;
  exercise: boolean;
  quizPassed: boolean;
  partColor: string;
  onStartQuiz?: () => void;
}

export default function PhaseGate({ read, exercise, quizPassed, partColor, onStartQuiz }: PhaseGateProps) {
  const phases = [
    { label: 'Read', done: read, icon: read ? CheckCircle2 : Circle },
    { label: 'Exercise', done: exercise, icon: exercise ? CheckCircle2 : Circle },
    { label: 'Quiz', done: quizPassed, icon: quizPassed ? CheckCircle2 : (!read || !exercise) ? Lock : Circle },
  ];

  return (
    <div className="glass-panel rounded-xl p-6 my-12">
      <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4">
        Chapter Progress
      </h3>
      <div className="flex items-center justify-between">
        {phases.map((phase, i) => (
          <div key={phase.label} className="flex items-center">
            <div className="flex flex-col items-center gap-2">
              <phase.icon
                className="w-6 h-6"
                style={{ color: phase.done ? partColor : 'hsl(var(--muted-foreground))' }}
              />
              <span className={`text-xs font-medium ${phase.done ? 'text-foreground' : 'text-muted-foreground'}`}>
                {phase.label}
              </span>
            </div>
            {i < phases.length - 1 && (
              <div
                className="w-16 lg:w-24 h-[1px] mx-4"
                style={{ backgroundColor: phase.done ? partColor : 'hsl(var(--border))' }}
              />
            )}
          </div>
        ))}
      </div>

      {read && exercise && !quizPassed && onStartQuiz && (
        <button
          onClick={onStartQuiz}
          className="mt-6 w-full py-3 rounded-lg font-semibold text-sm transition-all"
          style={{
            backgroundColor: `${partColor}20`,
            border: `1px solid ${partColor}50`,
            color: partColor,
          }}
        >
          Take Quiz &rarr;
        </button>
      )}

      {quizPassed && (
        <p className="mt-4 text-center text-sm" style={{ color: partColor }}>
          Chapter Complete
        </p>
      )}
    </div>
  );
}
