// app/components/chapter/SectionBlock.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { gsap } from 'gsap'
import { Eye } from 'lucide-vue-next'
import type { KeyConcept, ContentBlock, GlossaryTerm } from '~/types/chapter'

const props = defineProps<{
  id: string
  heading: string
  body: string
  blocks?: ContentBlock[]
  index: number
  totalSections?: number
  keyConcepts?: KeyConcept[]
  isActive?: boolean
  partColor?: string
  glossary?: GlossaryTerm[]
  chapterId?: string
}>()

const sectionRef = ref<HTMLElement | null>(null)
let ctx: gsap.Context | null = null

onMounted(() => {
  if (!sectionRef.value) return
  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches

  ctx = gsap.context(() => {
    gsap.from(sectionRef.value!, {
      y: prefersReducedMotion ? 0 : 40,
      opacity: prefersReducedMotion ? 1 : 0,
      duration: prefersReducedMotion ? 0 : 0.8,
      ease: 'power2.out',
      scrollTrigger: {
        trigger: sectionRef.value!,
        start: 'top 85%',
        once: true,
      },
    })
  })
})

onUnmounted(() => {
  ctx?.revert()
})

// Legacy fallback: split body by double newlines
const paragraphs = computed(() => props.body.split('\n\n'))
const hasRichBlocks = computed(() => props.blocks && props.blocks.length > 0)
</script>

<template>
  <section :id="id" ref="sectionRef" class="relative">
    <!-- Section divider (skip first section) -->
    <SectionDivider
      v-if="index > 0"
      :part-color="partColor ?? '#14b8a6'"
      :progress="(index + 1) / (totalSections || 10)"
    />

    <!-- Numbered heading with active indicator -->
    <div class="flex items-baseline gap-3 mb-5">
      <h2 class="font-display text-lg lg:text-xl font-semibold text-white flex items-baseline gap-3 flex-1">
        <span
          class="text-xs font-mono tabular-nums transition-colors duration-300"
          :class="isActive ? 'text-white/50' : 'text-white/20'"
        >
          {{ String(index + 1).padStart(2, '0') }}
        </span>
        {{ heading }}
        <!-- Active viz indicator -->
        <span
          v-if="isActive"
          class="inline-flex items-center gap-1 text-[9px] uppercase tracking-widest font-medium ml-auto opacity-0 lg:opacity-100 transition-opacity duration-500"
          :style="{ color: partColor ?? '#14b8a6' }"
        >
          <Eye class="w-2.5 h-2.5" />
          Viz
        </span>
      </h2>
      <!-- Notes for this section -->
      <NotesPanel
        v-if="chapterId"
        :chapter-id="chapterId"
        :section-id="id"
        :part-color="partColor ?? '#14b8a6'"
      />
    </div>

    <!-- Rich content blocks (new textbook format) -->
    <ContentRenderer v-if="hasRichBlocks" :blocks="blocks!" :glossary="glossary" />

    <!-- Legacy: plain text paragraphs -->
    <div v-else class="space-y-4">
      <p
        v-for="(para, pIdx) in paragraphs"
        :key="pIdx"
        class="text-sm leading-[1.8] text-white/60"
      >
        {{ para }}
      </p>
    </div>

    <!-- Key concepts -->
    <div
      v-if="keyConcepts && keyConcepts.length > 0"
      class="mt-6 space-y-3"
    >
      <div
        v-for="concept in keyConcepts"
        :key="concept.term"
        class="glass-panel concept-card rounded-lg p-4 border-l-2 transition-all duration-300 cursor-default"
        :style="{
          borderLeftColor: partColor ?? 'var(--color-primary)',
          '--concept-color': partColor ?? 'var(--color-primary)',
        }"
      >
        <h4
          class="concept-term text-xs font-semibold uppercase tracking-wider mb-1.5 transition-all duration-300"
          :style="{ color: partColor ?? 'var(--color-primary)' }"
        >
          {{ concept.term }}
        </h4>
        <p class="text-sm text-white/50 leading-relaxed">
          {{ concept.definition }}
        </p>
      </div>
    </div>
  </section>
</template>

<style scoped>
.concept-card {
  box-shadow: inset 2px 0 4px -2px transparent;
}

.concept-card:hover {
  transform: translateY(-1px);
  border-left-color: var(--concept-color) !important;
  box-shadow: inset 3px 0 8px -2px color-mix(in srgb, var(--concept-color) 30%, transparent),
              0 2px 12px rgba(0, 0, 0, 0.1);
}

.concept-card:hover .concept-term {
  text-shadow: 0 0 12px color-mix(in srgb, var(--concept-color) 40%, transparent);
}
</style>

// src/components/chapter/SectionBlock.tsx
'use client';
import { useRef } from 'react';
import { motion, useInView } from 'framer-motion';
import type { KeyConcept } from '@/types/chapter';

interface SectionBlockProps {
  id: string;
  heading: string;
  body: string;
  index: number;
  keyConcepts?: KeyConcept[];
}

export default function SectionBlock({ id, heading, body, index, keyConcepts }: SectionBlockProps) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-5% 0px -5% 0px' });

  return (
    <motion.section
      id={id}
      ref={ref}
      initial={{ opacity: 0, y: 24 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 24 }}
      transition={{ duration: 0.5, ease: [0.25, 0.1, 0.25, 1] }}
      className="mb-20"
    >
      {/* Section divider */}
      {index > 0 && <div className="section-divider mb-10" />}

      {/* Heading */}
      <h2 className="text-[22px] font-semibold mb-5 text-foreground flex items-baseline gap-3">
        <span className="text-primary/30 text-sm font-mono tabular-nums">
          {String(index + 1).padStart(2, '0')}
        </span>
        {heading}
      </h2>

      {/* Body paragraphs */}
      <div className="text-muted-foreground text-[15px] leading-[1.8] space-y-5">
        {body.split('\n\n').map((paragraph, i) => (
          <p key={i}>{paragraph}</p>
        ))}
      </div>

      {/* Key concepts */}
      {keyConcepts && keyConcepts.length > 0 && (
        <div className="mt-8 space-y-3">
          {keyConcepts.map((concept) => (
            <div
              key={concept.term}
              className="glass-panel concept-glow rounded-lg p-5 border-l-2 transition-shadow duration-300"
              style={{ borderLeftColor: 'hsl(228, 100%, 64%)' }}
            >
              <dt className="text-sm font-semibold text-foreground mb-1.5">{concept.term}</dt>
              <dd className="text-sm text-muted-foreground leading-relaxed">{concept.definition}</dd>
            </div>
          ))}
        </div>
      )}
    </motion.section>
  );
}
