// src/components/chapter/ChapterNav.tsx
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Globe } from 'lucide-react';
import type { ChapterMeta } from '@/types/chapter';

interface ChapterNavProps {
  prevChapter?: ChapterMeta;
  nextChapter?: ChapterMeta;
}

export default function ChapterNav({ prevChapter, nextChapter }: ChapterNavProps) {
  return (
    <div className="mt-16 pt-8 border-t border-border">
      <div className="flex items-center justify-between gap-4">
        {prevChapter ? (
          <Link
            href={`/chapter/${prevChapter.slug}`}
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <div>
              <span className="text-xs text-muted-foreground/60 block">Previous</span>
              <span>{prevChapter.title}</span>
            </div>
          </Link>
        ) : (
          <div />
        )}

        <Link
          href="/"
          className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground transition-colors"
        >
          <Globe className="w-3.5 h-3.5" />
          Universe
        </Link>

        {nextChapter ? (
          <Link
            href={`/chapter/${nextChapter.slug}`}
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors group text-right"
          >
            <div>
              <span className="text-xs text-muted-foreground/60 block">Next</span>
              <span>{nextChapter.title}</span>
            </div>
            <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </Link>
        ) : (
          <div />
        )}
      </div>
    </div>
  );
}

// components/chapter/ChapterNav.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ArrowLeft, ArrowRight } from 'lucide-vue-next'
import { getNextChapter, getPrevChapter, getPartForChapter } from '~/lib/chapter-utils'

const props = defineProps<{
  currentSlug: string
}>()

const prev = computed(() => getPrevChapter(props.currentSlug))
const next = computed(() => getNextChapter(props.currentSlug))
const prevPart = computed(() => prev.value ? getPartForChapter(prev.value.id) : null)
const nextPart = computed(() => next.value ? getPartForChapter(next.value.id) : null)
</script>

<template>
  <nav class="mt-16 mb-8" aria-label="Chapter navigation">
    <div class="section-divider mb-8" />

    <div class="flex items-stretch gap-3">
      <!-- Previous chapter -->
      <NuxtLink
        v-if="prev"
        :to="`/chapter/${prev.slug}`"
        class="flex-1 glass-panel rounded-xl px-5 py-4 flex items-center gap-3 transition-all duration-200 hover:bg-white/[0.03] hover:border-white/10 group"
        :aria-label="`Previous chapter: ${prev.title}`"
      >
        <ArrowLeft class="w-4 h-4 text-white/25 group-hover:text-white/50 transition-colors shrink-0" />
        <div class="min-w-0">
          <span class="text-[10px] text-white/30 uppercase tracking-wider">Previous</span>
          <p class="text-sm font-medium text-white/70 group-hover:text-white/90 transition-colors truncate">
            {{ prev.title }}
          </p>
        </div>
      </NuxtLink>

      <!-- Spacer when no prev -->
      <div v-else class="flex-1" />

      <!-- Next chapter -->
      <NuxtLink
        v-if="next"
        :to="`/chapter/${next.slug}`"
        class="flex-1 glass-panel rounded-xl px-5 py-4 flex items-center justify-end gap-3 text-right transition-all duration-200 hover:bg-white/[0.03] hover:border-white/10 group"
        :aria-label="`Next chapter: ${next.title}`"
      >
        <div class="min-w-0">
          <span class="text-[10px] text-white/30 uppercase tracking-wider">Next</span>
          <p class="text-sm font-medium text-white/70 group-hover:text-white/90 transition-colors truncate">
            {{ next.title }}
          </p>
        </div>
        <ArrowRight class="w-4 h-4 text-white/25 group-hover:text-white/50 transition-colors shrink-0" />
      </NuxtLink>

      <!-- Spacer when no next -->
      <div v-else class="flex-1" />
    </div>
  </nav>
</template>
